services:
  frontend:
    image: note-frontend:${IMAGE_TAG}  # Use pre-built frontend image with dynamic tag
    ports:
      - "3000:3000"  # Expose frontend port
    environment:
      - FRONTEND_API_URL=${VITE_API_URL}  # Assuming you are passing a port for the frontend
    depends_on:
      - backend

  backend:
    image: note-backend:${IMAGE_TAG}  # Use pre-built backend image with dynamic tag
    ports:
      - "${PORT}:${PORT}"  # Expose the backend port dynamically using the environment variable
    environment:
      - NODE_ENV=production
      - PORT=${PORT}  # Use the secret file for PORT
      - dbName=${dbName}  # Use the secret file for dbName
      - MONGO_URI=${MONGO_URI}
    networks:
      - app-network

secrets:
  port_secret:
    external: true  # The secret for PORT
  dbname_secret:
    external: true  # The secret for dbName
  mongo_uri_secret:
    external: true  # The secret for MONGO_URI

networks:
  app-network:
    driver: bridge  # Use bridge network for local communication






